### ISSUE TITLE
Admin Content section dropdowns do not update on value changed

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo#1]
The dropdowns do not update on value changed in the admin content tab

This should be handled by AJAX. Php code in place to generate XML

**Comment by mwauramuchiri** [comment]
I noticed the status never became 200 at any time.
I'm not sure why

**Comment by AllanJeremy** [comment]
Not sure either. Just tested it. Still not working. Need a solution to this pretty soon

**Comment by AllanJeremy** [comment]
@mwauramuchiri confirm when it is full functional

**Comment by mwauramuchiri** [comment]
It is fully functional on my side.

**Comment by mwauramuchiri** [comment]
@AllanJeremy

**Comment by AllanJeremy** [comment]
Cool. Push it to user-frontend so that I can test it

**Comment by mwauramuchiri** [comment]
i think I have done that now. Check tell me

**Comment by AllanJeremy** [comment]
Works now,
