### ISSUE TITLE
Search in statistics page does not work

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo#19]
The search in the statistics page does not work. Nothing is highlighted when searching, however when the record is not found in the database, it displays 'nothing found' multiple times

Note if possible, it should display nothing found once only, I'll try fixing that at the very least. Will discuss the no highlight and whether it should filter

**Comment by AllanJeremy** [comment]
Fixed the issue mentioned 

> Note if possible, it should display nothing found once only

this was **after** the issue was fixed 
![screenshot_10](https://cloud.githubusercontent.com/assets/5031274/17200425/cbdb41c0-548d-11e6-9da0-39b44c16a003.png)

**and before**
![screenshot_9](https://cloud.githubusercontent.com/assets/5031274/17200414/ad96c022-548d-11e6-8f79-18d4fdf4a2d1.png)

**Comment by AllanJeremy** [comment]
Noted another issue, the first time the page loads. You have to double click the search button for the search to work

**Comment by mwauramuchiri** [comment]
the issue was that it was highlighting but the css to show the highlights could not be found. fixed it

**Comment by mwauramuchiri** [comment]
thanks for that fix.
Imenisumbua for a while

**Comment by mwauramuchiri** [comment]
the double click...
If there's a way of getting the id of the button clicked without using $('button').click(...
That would fix it.
The id of the button clicked is crucial.
