### ISSUE TITLE
To change password hashing function and validation

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo#2]
Currently the `crypt()` function is being used with the generated salt being saved in the database. In future implementations, this function is to be replaced with the stronger `password_hash`and validation is to be done using `hash_equals`

**Comment by mwauramuchiri** [comment]
I have used password_hash() on the signup. works fine.
another issue encountered is 
500 Error [Server error]. Unable to get records from database, try again later
If the problem persists, contact the system administrator. Error code : 61311 error in this if else statement.
I used password_verify() which works.
if (loginValid()===true)
    {
        login();#login then exit the file
        exit;
    }
    else if (loginValid()===false)//incorrect login credentials
    {
        header('Location: invalidLogin.php');
        exit;
    }
    else
    {
        echo "<p><b>500 Error [Server error]</b>. Unable to get records from database, try again later</p>If the problem persists, <a>contact the system administrator</a>. Error code : 61311";
    }

**Comment by AllanJeremy** [comment]
Alright. Works on my side. Try using the new esomo_base_data.sql database
