### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo#20]
Should have a functional local upload system that can be tweaked to upload to cloud.

This allows admins to upload content for assignments and articles/books/videos

**Comment by AllanJeremy** [comment]
Basic upload system working for one file input(content_files) but failing for other(assignments). Admin can only upload one file at a time

Created a file in admin/handlers called `fileUpload.php` which contains a class `FileUpload` which in turn contains functions that are used to handle uploading of files

**Comment by AllanJeremy** [comment]
Fixed the issue with 

> working for one file input(content_files) but failing for other(assignments)

**Comment by mwauramuchiri** [comment]
The merged update has this feature
