### ISSUE TITLE
Content needs overflow fixed

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo#8]
Content tab in the learn section does not adjust its overflow to match the child elements. To add class clearfix

**Comment by mwauramuchiri** [comment]
What do you mean?

**Comment by AllanJeremy** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/5031274/17068520/171b7bd8-505a-11e6-9c8b-6edce31beee9.png)

**Comment by AllanJeremy** [comment]
Fixed it
![screenshot_2](https://cloud.githubusercontent.com/assets/5031274/17068665/ec4e2300-505a-11e6-97f3-b36413506d2b.png)
